global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RAG API metrics
  - job_name: 'rag-api'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Prometheus metrics from RAG API
    scrape_interval: 5s
    metrics_path: /metrics

  # FastAPI application metrics  
  - job_name: 'rag-fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 5s
    metrics_path: /prometheus-metrics

  # Milvus metrics
  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis metrics (if redis-exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    
  # PostgreSQL metrics (if postgres-exporter is used)  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for common queries
rule_files:
  - "/etc/prometheus/recording_rules.yml"
  - "/etc/prometheus/alerting_rules.yml"
